services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: Dockerfile.backend
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ${RENDER_POSTGRESQL_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${RENDER_POSTGRESQL_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${RENDER_POSTGRESQL_PASSWORD}
    plan: free

  - name: frontend
    type: web
    env: docker
    dockerfilePath: pingme-frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: nginx -g "daemon off;"
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://backend.onrender.com
    plan: free

